import type { EtfKnowledgeRecord } from './types'

const now = new Date().toISOString()
const master = (id:string,ticker:string,fundName:string,issuer:string,strategy:string,assetClass:string,frequency:EtfKnowledgeRecord['master']['distributionFrequency']):EtfKnowledgeRecord['master'] => ({
  id,ticker,fundName,issuer,strategy,primaryAssetClass:assetClass,distributionFrequency:frequency,status:'Active',currency:'USD',lastUpdatedAt:now,sourceId:'demo-seed'
})

export const ETF_KNOWLEDGE_SEED: EtfKnowledgeRecord[] = [
  { master: master('demo-edgq','EDGQ','Income & Growth ETF','Demo Dataset','Equity income and growth','Equity','Weekly'), classification:{etfId:'demo-edgq',incomeStyles:['Dividend Growth'],growthThemes:[],marketSegments:['US Large Cap'],optionStrategies:['None'],leverageType:'None',tags:['income','growth','weekly']}, risk:{etfId:'demo-edgq',overallBand:'Moderate',volatilityScore:45,navStabilityScore:70,distributionStabilityScore:68,leverageRiskScore:5,optionsComplexityScore:10,interestRateRiskScore:15,currencyRiskScore:5,liquidityRiskScore:35,concentrationRiskScore:40,issuerRiskScore:30,rationale:['Balanced demo profile'],calculatedAt:now}, intelligence:{etfId:'demo-edgq',labels:['Income + Growth','Core Candidate'],strengths:['Weekly distribution schedule','Balanced mandate'],considerations:['Demo record pending verified provider data']} },
  { master: master('demo-xdte','XDTE','S&P 500 0DTE Covered Call','Demo Dataset','Same-day option income','Equity','Weekly'), classification:{etfId:'demo-xdte',incomeStyles:['Covered Call','Option Income'],growthThemes:[],marketSegments:['US Large Cap'],optionStrategies:['0DTE Covered Call'],leverageType:'None',tags:['covered-call','0dte','weekly']}, risk:{etfId:'demo-xdte',overallBand:'Elevated',volatilityScore:58,navStabilityScore:50,distributionStabilityScore:55,leverageRiskScore:15,optionsComplexityScore:75,interestRateRiskScore:10,currencyRiskScore:5,liquidityRiskScore:30,concentrationRiskScore:50,issuerRiskScore:30,rationale:['Complex option overlay'],calculatedAt:now}, intelligence:{etfId:'demo-xdte',labels:['Income Focused','Satellite Candidate','Research Required'],strengths:['Frequent cash-flow profile'],considerations:['Option strategy may limit upside','Demo record pending verified provider data']} },
  { master: master('demo-kyld','KYLD','Yield Premium Strategy ETF','Demo Dataset','Option-premium equity income','Equity','Weekly'), classification:{etfId:'demo-kyld',incomeStyles:['Covered Call','Option Income'],growthThemes:[],marketSegments:['US Large Cap'],optionStrategies:['Traditional Covered Call'],leverageType:'None',tags:['covered-call','weekly']}, risk:{etfId:'demo-kyld',overallBand:'Elevated',volatilityScore:60,navStabilityScore:48,distributionStabilityScore:54,leverageRiskScore:10,optionsComplexityScore:65,interestRateRiskScore:10,currencyRiskScore:5,liquidityRiskScore:45,concentrationRiskScore:55,issuerRiskScore:35,rationale:['Income depends on option premium'],calculatedAt:now}, intelligence:{etfId:'demo-kyld',labels:['Income Focused','Satellite Candidate'],strengths:['Weekly income orientation'],considerations:['Monitor NAV and distribution stability','Demo record pending verified provider data']} },
  { master: master('demo-bccc','BCCC','Crypto Income Strategy ETF','Demo Dataset','Crypto-linked option income','Digital Asset Exposure','Weekly'), classification:{etfId:'demo-bccc',incomeStyles:['Option Income'],growthThemes:[],marketSegments:['Thematic'],optionStrategies:['Synthetic Covered Call'],leverageType:'Other',tags:['crypto','options','weekly']}, risk:{etfId:'demo-bccc',overallBand:'Very High',volatilityScore:90,navStabilityScore:25,distributionStabilityScore:42,leverageRiskScore:55,optionsComplexityScore:85,interestRateRiskScore:5,currencyRiskScore:5,liquidityRiskScore:50,concentrationRiskScore:85,issuerRiskScore:40,rationale:['Crypto-linked exposure','Complex derivatives'],calculatedAt:now}, intelligence:{etfId:'demo-bccc',labels:['Income Focused','Elevated Risk','Research Required'],strengths:['High income potential'],considerations:['High volatility','Potential NAV instability','Demo record pending verified provider data']} },
]
