import type { StrategyCandidate } from './types'

// Modeled placeholders only. The full-universe provider pipeline will replace these assumptions with verified data.
export const STRATEGY_CANDIDATES: StrategyCandidate[] = [
  {ticker:'CORE',name:'Broad U.S. Equity Core (model)',issuer:'Model Provider A',category:'Core Equity',sector:'Broad Market',distributionFrequency:'Quarterly',modeledYieldPct:1.6,modeledGrowthPct:7.0,stabilityScore:88,riskScore:42,expenseRatioPct:.05,coveredCall:false,fixedIncome:false,growthAsset:true},
  {ticker:'DIVG',name:'Dividend Growth Equity (model)',issuer:'Model Provider B',category:'Dividend Growth',sector:'Broad Market',distributionFrequency:'Quarterly',modeledYieldPct:3.4,modeledGrowthPct:5.2,stabilityScore:86,riskScore:38,expenseRatioPct:.18,coveredCall:false,fixedIncome:false,growthAsset:true},
  {ticker:'EQWK',name:'Weekly Equity Income (model)',issuer:'Model Provider C',category:'Covered Call',sector:'Broad Market',distributionFrequency:'Weekly',modeledYieldPct:12.5,modeledGrowthPct:1.8,stabilityScore:66,riskScore:62,expenseRatioPct:.65,coveredCall:true,fixedIncome:false,growthAsset:false},
  {ticker:'TECH',name:'Technology Income Overlay (model)',issuer:'Model Provider D',category:'Covered Call',sector:'Technology',distributionFrequency:'Weekly',modeledYieldPct:16.0,modeledGrowthPct:1.2,stabilityScore:55,riskScore:72,expenseRatioPct:.85,coveredCall:true,fixedIncome:false,growthAsset:false},
  {ticker:'BOND',name:'Investment Grade Bond (model)',issuer:'Model Provider A',category:'Fixed Income',sector:'Fixed Income',distributionFrequency:'Monthly',modeledYieldPct:4.8,modeledGrowthPct:.5,stabilityScore:91,riskScore:24,expenseRatioPct:.12,coveredCall:false,fixedIncome:true,growthAsset:false},
  {ticker:'TRSY',name:'Short Treasury Income (model)',issuer:'Model Provider E',category:'Fixed Income',sector:'Fixed Income',distributionFrequency:'Monthly',modeledYieldPct:4.2,modeledGrowthPct:.2,stabilityScore:96,riskScore:12,expenseRatioPct:.10,coveredCall:false,fixedIncome:true,growthAsset:false},
  {ticker:'PREF',name:'Preferred Securities Income (model)',issuer:'Model Provider F',category:'Preferreds',sector:'Financials',distributionFrequency:'Monthly',modeledYieldPct:6.7,modeledGrowthPct:1.0,stabilityScore:73,riskScore:49,expenseRatioPct:.45,coveredCall:false,fixedIncome:false,growthAsset:false},
  {ticker:'REIT',name:'Real Estate Income (model)',issuer:'Model Provider G',category:'REIT',sector:'Real Estate',distributionFrequency:'Monthly',modeledYieldPct:5.3,modeledGrowthPct:2.5,stabilityScore:70,riskScore:53,expenseRatioPct:.38,coveredCall:false,fixedIncome:false,growthAsset:true},
  {ticker:'ALTW',name:'Alternative Weekly Income (model)',issuer:'Model Provider H',category:'Alternative Income',sector:'Alternatives',distributionFrequency:'Weekly',modeledYieldPct:20.0,modeledGrowthPct:-1.5,stabilityScore:42,riskScore:88,expenseRatioPct:1.05,coveredCall:false,fixedIncome:false,growthAsset:false},
]
