import { CalendarDays, Plus, RefreshCw, Trash2, X } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { validateDistribution } from '../features/distributions/distributionEngine'
import type { DistributionFrequency, DistributionStatus } from '../types/distribution'
import { usePortfolio, usePortfolioMetrics } from '../features/portfolio/PortfolioContext'
const money=(v:number,d=0)=>v.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:d})
const today=new Date().toISOString().slice(0,10)
export function CalendarPage(){
 const {holdings,distributions,recordDistribution,removeDistribution,syncDistributions,distributionSyncState,distributionSyncError,distributionSyncedAt,lastDistributionSync}=usePortfolio();const m=usePortfolioMetrics();const [range,setRange]=useState<'week'|'month'|'quarter'>('month');const [open,setOpen]=useState(false);const [errors,setErrors]=useState<string[]>([])
 const days=range==='week'?7:range==='month'?35:91;const cutoff=new Date(Date.now()+days*864e5).toISOString().slice(0,10);const visible=useMemo(()=>m.incomeProjection.events.filter(e=>e.paymentDate>=today&&e.paymentDate<=cutoff),[m.incomeProjection.events,cutoff])
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const draft={ticker:String(f.get('ticker')).toUpperCase(),amountPerShare:Number(f.get('amountPerShare')),declarationDate:String(f.get('declarationDate'))||null,exDate:String(f.get('exDate'))||null,recordDate:String(f.get('recordDate'))||null,paymentDate:String(f.get('paymentDate')),frequency:String(f.get('frequency')) as DistributionFrequency,status:String(f.get('status')) as DistributionStatus,source:String(f.get('source')),notes:String(f.get('notes'))};const next=validateDistribution(draft);setErrors(next);if(next.length)return;await recordDistribution(draft);setOpen(false)}
 return <div><section className="page-heading"><div><span className="eyebrow">DISTRIBUTION INTELLIGENCE</span><h1>Income Calendar</h1><p>Track declared distributions and project portfolio cash flow across upcoming payment dates.</p></div><div className="heading-actions"><button className="secondary-button" onClick={()=>void syncDistributions()} disabled={distributionSyncState==='syncing'}><RefreshCw size={15}/>{distributionSyncState==='syncing'?' Syncing…':' Sync provider data'}</button><button className="gold-button" onClick={()=>{setErrors([]);setOpen(true)}}><Plus size={15}/> Add distribution</button></div></section>
 <section className="panel sync-status-panel"><div><span className="eyebrow">AUTOMATED DISTRIBUTION SYNC</span><strong>{distributionSyncState==='fallback'?'Sandbox fallback active':distributionSyncState==='synced'?'Provider data synchronized':distributionSyncState==='error'?'Sync requires attention':'Ready to synchronize'}</strong><small>{distributionSyncedAt?`Last sync ${new Date(distributionSyncedAt).toLocaleString()}`:'No automated sync has run yet.'}</small></div>{lastDistributionSync&&<div className="sync-stats"><span>{lastDistributionSync.summary.inserted} added</span><span>{lastDistributionSync.summary.updated} revised</span><span>{lastDistributionSync.summary.skippedManual} manual protected</span><span>{lastDistributionSync.summary.rejected} rejected</span></div>}{distributionSyncError&&<p className="error-text">{distributionSyncError}</p>}</section><section className="metric-grid small"><article className="metric-card simple"><span>Next 90 days</span><strong>{money(m.incomeProjection.projectedNext90Days)}</strong></article><article className="metric-card simple"><span>Confirmed</span><strong>{money(m.incomeProjection.confirmedNext90Days)}</strong></article><article className="metric-card simple"><span>Annualized</span><strong>{money(m.annualIncome)}</strong></article><article className="metric-card simple"><span>Distribution records</span><strong>{distributions.length}</strong></article></section>
 <section className="calendar2-toolbar">{(['week','month','quarter'] as const).map(x=><button className={range===x?'active':''} onClick={()=>setRange(x)} key={x}>{x}</button>)}</section>
 <section className="calendar2-layout"><article className="panel calendar2-events"><div className="panel-heading"><h3><CalendarDays size={16}/> Upcoming payments</h3><span>{visible.length} events</span></div>{visible.map(e=><div key={e.id}><time>{new Date(`${e.paymentDate}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</time><b>{e.ticker}</b><span>{e.confidence}</span><strong>{money(e.projectedIncome)}</strong><small>{money(e.amountPerShare,4)}/share</small></div>)}{!visible.length&&<div className="empty-state"><strong>No payments in this range</strong><span>Add a declared distribution or extend the calendar range.</span></div>}</article><article className="panel calendar2-summary"><small>VISIBLE CASH FLOW</small><strong>{money(visible.reduce((s,e)=>s+e.projectedIncome,0))}</strong><p>Confirmed events use saved declarations. Projected events extend the latest known cadence and amount.</p></article></section>
 <section className="panel transaction-panel"><div className="panel-heading"><div><h3>Distribution History</h3><small>Declared, paid, and estimated records</small></div><span>{distributions.length} records</span></div><div className="transaction-list">{distributions.slice(0,20).map(d=><div className="transaction-row" key={d.id}><span><strong>{d.ticker}</strong><small>{d.paymentDate}</small></span><span><b>{d.status.toUpperCase()}</b><small>{d.frequency} · {d.providerId||d.source||'Manual'}{d.revision&&d.providerId?` · rev ${d.revision}`:''}</small></span><span className="positive">{money(d.amountPerShare,4)}/share</span><button className="delete-button" onClick={()=>void removeDistribution(d.id)} aria-label={`Delete ${d.ticker} distribution`}><Trash2 size={14}/></button></div>)}{!distributions.length&&<div className="empty-state"><strong>No saved distributions</strong><span>The engine currently uses each holding’s annual distribution assumption.</span></div>}</div></section>
 {open&&<div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-title"><div><span className="eyebrow">DISTRIBUTION RECORD</span><h2>Add Distribution</h2></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><X/></button></div>{errors.length>0&&<div className="form-errors">{errors.map(error=><p key={error}>{error}</p>)}</div>}<div className="form-grid"><label>Ticker<select name="ticker" defaultValue={holdings[0]?.ticker??''}>{holdings.map(h=><option key={h.id}>{h.ticker}</option>)}</select></label><label>Amount per share<input name="amountPerShare" type="number" min="0.000001" step="0.000001" required/></label><label>Payment date<input name="paymentDate" type="date" required defaultValue={today}/></label><label>Ex-dividend date<input name="exDate" type="date"/></label><label>Record date<input name="recordDate" type="date"/></label><label>Declaration date<input name="declarationDate" type="date"/></label><label>Frequency<select name="frequency" defaultValue="Weekly"><option>Weekly</option><option>Monthly</option><option>Quarterly</option><option>Irregular</option></select></label><label>Status<select name="status" defaultValue="declared"><option value="declared">Declared</option><option value="paid">Paid</option><option value="estimated">Estimated</option></select></label><label>Source<input name="source" placeholder="Fund sponsor or broker"/></label><label>Notes<input name="notes" placeholder="Special or regular distribution"/></label></div><button className="gold-button full" type="submit">Save Distribution</button></form></div>}
 </div>}
