import { useMemo, useState } from 'react'
import { Activity, Copy, Gauge, GitCompareArrows, Play, Plus, ShieldCheck, TrendingUp, WalletCards } from 'lucide-react'
import { projectScenario, runMonteCarlo } from '../domain/digital-twin/engine'
import { TWIN_SCENARIOS } from '../domain/digital-twin/seed'

const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n)
export function DigitalTwinPage(){
 const [selected,setSelected]=useState(TWIN_SCENARIOS[0].id)
 const scenario=TWIN_SCENARIOS.find(s=>s.id===selected)!
 const projection=useMemo(()=>projectScenario(scenario),[scenario])
 const monte=useMemo(()=>runMonteCarlo(scenario,1000),[scenario])
 const max=Math.max(...projection.points.map(p=>p.closingValue),1)
 const poly=projection.points.map((p,i)=>`${(i/Math.max(1,projection.points.length-1))*100},${95-(p.closingValue/max)*80}`).join(' ')
 return <div className="digital-twin-page">
  <section className="page-heading"><div><span className="eyebrow">PROGRAM B · INCOME DIGITAL TWIN 2.0</span><h1>Model your financial future before you live it</h1><p>Clone portfolios, compare retirement paths, test withdrawals, inflation, taxes, contributions, life events and sequence-of-returns risk.</p></div><div className="program-a-badge"><Activity size={18}/><span>Version 20</span><strong>Digital Twin 2.0</strong></div></section>
  <section className="twin-actions"><button><Plus size={16}/>New scenario</button><button><Copy size={16}/>Clone scenario</button><button><GitCompareArrows size={16}/>Compare twins</button><button className="primary"><Play size={16}/>Run simulation</button></section>
  <section className="scenario-tabs">{TWIN_SCENARIOS.map(s=><button className={selected===s.id?'active':''} onClick={()=>setSelected(s.id)} key={s.id}><strong>{s.name}</strong><span>{s.kind}</span></button>)}</section>
  <section className="program-a-metrics"><article className="panel"><WalletCards/><div><small>Projected ending value</small><strong>{money(projection.endingValue)}</strong><span>{money(projection.endingRealValue)} inflation-adjusted</span></div></article><article className="panel"><TrendingUp/><div><small>Lifetime distributions</small><strong>{money(projection.totalIncome)}</strong><span>{money(projection.totalWithdrawals)} withdrawals</span></div></article><article className="panel"><ShieldCheck/><div><small>Sustainability score</small><strong>{projection.sustainabilityScore}</strong><span>{projection.goalStatus}</span></div></article><article className="panel"><Gauge/><div><small>Monte Carlo success</small><strong>{monte.successRate}%</strong><span>{monte.trials.toLocaleString()} deterministic-seed trials</span></div></article></section>
  <section className="program-a-grid"><article className="panel history-terminal"><div className="panel-title"><div><span className="eyebrow">LONG-RANGE FORECAST</span><h2>Portfolio value path</h2></div></div><svg className="history-sparkline" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={poly}/></svg><div className="history-stats"><div><small>Start age</small><strong>{scenario.assumptions.startAge}</strong></div><div><small>Retirement</small><strong>{scenario.assumptions.retirementAge}</strong></div><div><small>Years modeled</small><strong>{scenario.assumptions.years}</strong></div><div><small>Reinvestment</small><strong>{scenario.assumptions.reinvestmentRate*100}%</strong></div></div></article><article className="panel"><div className="panel-title"><div><span className="eyebrow">RANGE OF OUTCOMES</span><h2>Monte Carlo envelope</h2></div></div><div className="twin-range"><div><small>10th percentile</small><strong>{money(monte.percentile10)}</strong></div><div><small>Median</small><strong>{money(monte.medianEndingValue)}</strong></div><div><small>90th percentile</small><strong>{money(monte.percentile90)}</strong></div></div><p className="data-disclaimer">Simulation results are modeled scenarios, not forecasts or guarantees. Production use requires validated market assumptions and user-specific tax review.</p></article></section>
  <section className="panel twin-ledger"><div className="panel-title"><div><span className="eyebrow">ANNUAL CASH-FLOW LEDGER</span><h2>Projection checkpoints</h2></div></div><div className="program-a-row program-a-head"><span>Year / age</span><span>Opening value</span><span>Income</span><span>Contributions</span><span>Withdrawals</span><span>Closing value</span></div>{projection.points.filter((_,i)=>i<5||i%5===4||i===projection.points.length-1).map(p=><div className="program-a-row" key={p.year}><strong>Year {p.year}<small>Age {p.age}</small></strong><span>{money(p.openingValue)}</span><span>{money(p.distributions)}</span><span>{money(p.contributions)}</span><span>{money(p.withdrawals)}</span><span><b>{money(p.closingValue)}</b><small>{money(p.realValue)} real</small></span></div>)}</section>
 </div>
}
