import { useMemo, useState } from 'react'
import { Bot, Building2, Database, FlaskConical, Gauge, Layers3, Network, ShieldCheck, Sparkles } from 'lucide-react'
import { usePortfolio, usePortfolioMetrics } from '../features/portfolio/PortfolioContext'
import { calculateIncomeOSScore } from '../domain/operating-score/incomeOperatingSystemScore'
import { runIncomeDigitalTwin } from '../domain/digital-twin/incomeDigitalTwin'
import { buildAttribution } from '../domain/portfolio-intelligence/attribution'
import { enterpriseReadiness } from '../domain/enterprise/platformContracts'

const tracks=[['1','Core Platform','Workspace model and modular dashboard foundation',Layers3],['2','ETF Universe','Research-ready normalized knowledge layer',Database],['3','Income Copilot','Intent routing and tool orchestration',Bot],['4','Income Digital Twin','Persistent what-if simulation engine',FlaskConical],['5','Portfolio Intelligence','Income and allocation attribution',Network],['6','Research Engine','Evidence-aware ETF research profiles',Sparkles],['7','Income OS Score','Ten explainable scoring dimensions',Gauge],['8','Advisor Platform','Client and household domain models',Building2],['9','Enterprise Infrastructure','Provider, sync, audit, and feature-flag contracts',ShieldCheck]] as const
export function EnterpriseBuildPage(){
 const {holdings,weeklyGoal}=usePortfolio();const m=usePortfolioMetrics();const score=useMemo(()=>calculateIncomeOSScore(holdings,m.weeklyIncome,weeklyGoal),[holdings,m.weeklyIncome,weeklyGoal]);const attribution=useMemo(()=>buildAttribution(holdings),[holdings]);
 const [years,setYears]=useState(10);const twin=useMemo(()=>runIncomeDigitalTwin('Baseline Twin',holdings,{years,annualGrowthPct:4,distributionGrowthPct:2,reinvestPct:25,monthlyContribution:0,stressDrawdownPct:0}),[holdings,years])
 return <div><div className="page-heading"><div><span className="eyebrow">ENTERPRISE BUILD PROGRAM</span><h1>Tracks 1–9 Development Center</h1><p>Working foundations for the integrated Income Operating System.</p></div><span className="live-badge">OFFLINE INCREMENT ACTIVE</span></div>
 <section className="track-grid">{tracks.map(([n,title,detail,Icon])=><article className="panel track-card" key={n}><Icon size={20}/><small>TRACK {n}</small><strong>{title}</strong><p>{detail}</p><span>FOUNDATION BUILT</span></article>)}</section>
 <section className="enterprise-grid"><article className="panel"><div className="panel-title"><span>INCOME OPERATING SYSTEM SCORE™</span><b>{score.total} · {score.grade}</b></div><div className="score-dimensions">{score.dimensions.map(d=><div key={d.key}><label><span>{d.label}</span><b>{Math.round(d.score)}</b></label><i><em style={{width:`${d.score}%`}}/></i></div>)}</div><p className="muted-copy"><b>Strongest:</b> {score.strongest.label}. <b>Next improvement:</b> {score.weakest.improvement}</p></article>
 <article className="panel"><div className="panel-title"><span>INCOME DIGITAL TWIN™</span><b>{years} YEARS</b></div><label className="range-label">Projection horizon <input type="range" min="1" max="30" value={years} onChange={e=>setYears(Number(e.target.value))}/></label><div className="twin-results"><div><small>ENDING VALUE</small><strong>${twin.endingValue.toLocaleString(undefined,{maximumFractionDigits:0})}</strong></div><div><small>ENDING WEEKLY INCOME</small><strong>${twin.endingWeeklyIncome.toLocaleString(undefined,{maximumFractionDigits:0})}</strong></div><div><small>REINVESTMENT</small><strong>25%</strong></div><div><small>MODE</small><strong>SIMULATION</strong></div></div><p className="muted-copy">The twin is isolated from the real portfolio and uses editable modeled assumptions.</p></article></section>
 <section className="enterprise-grid"><article className="panel"><div className="panel-title"><span>INCOME ATTRIBUTION</span><b>TOP CONTRIBUTORS</b></div><div className="attribution-list">{attribution.map(r=><div key={r.ticker}><b>{r.ticker}</b><span>{r.category}</span><em>{r.incomeWeight.toFixed(1)}% of income</em><strong>${r.annualIncome.toFixed(0)}</strong></div>)}</div></article><article className="panel"><div className="panel-title"><span>ENTERPRISE READINESS</span><b>ARCHITECTURE</b></div><div className="readiness-list">{enterpriseReadiness.map(x=><div key={x.area}><span>{x.area}</span><b>{x.status}</b></div>)}</div></article></section>
 </div>
}
