import { useMemo, useState } from 'react'
import { Activity, AlertTriangle, Bot, CalendarClock, CircleDollarSign, Gauge, Send, Sparkles, TrendingUp } from 'lucide-react'
import { usePortfolio, usePortfolioMetrics } from '../features/portfolio/PortfolioContext'
import { buildCashEvents, buildMissionAlerts } from '../domain/mission-control/missionControl'
import { askIncomeCopilot } from '../domain/copilot/incomeCopilot'
import { PortfolioHealthCard } from '../components/command/PortfolioHealthCard'

export function MissionControlPage(){
 const {holdings,weeklyGoal}=usePortfolio(); const m=usePortfolioMetrics(); const events=useMemo(()=>buildCashEvents(holdings),[holdings]); const alerts=useMemo(()=>buildMissionAlerts(holdings,m.weeklyIncome,weeklyGoal),[holdings,m.weeklyIncome,weeklyGoal]); const [q,setQ]=useState('What is my biggest risk?'); const [answer,setAnswer]=useState(()=>askIncomeCopilot(q,holdings,m.weeklyIncome,weeklyGoal));
 const submit=()=>setAnswer(askIncomeCopilot(q,holdings,m.weeklyIncome,weeklyGoal))
 return <div className="mission-page"><div className="page-heading"><div><span className="eyebrow">INCOME OS · PRIMARY WORKSPACE</span><h1>Income Mission Control</h1><p>One operating view for cash flow, risk, goals, intelligence, and your next decision.</p></div><span className="live-badge"><Activity size={14}/> OFFLINE MODEL ACTIVE</span></div>
 <section className="mission-kpis"><article><CircleDollarSign/><small>PORTFOLIO VALUE</small><strong>${m.portfolioValue.toLocaleString(undefined,{maximumFractionDigits:0})}</strong><span>{m.gainLoss>=0?'+':''}${m.gainLoss.toLocaleString(undefined,{maximumFractionDigits:0})} unrealized</span></article><article><TrendingUp/><small>WEEKLY INCOME</small><strong>${m.weeklyIncome.toFixed(0)}</strong><span>{m.goalProgress.toFixed(1)}% of goal</span></article><article><CalendarClock/><small>NEXT 30 DAYS</small><strong>${events.filter(e=>new Date(e.date).getTime()-Date.now()<30*864e5).reduce((s,e)=>s+e.amount,0).toFixed(0)}</strong><span>{events.length} modeled events</span></article><article><Gauge/><small>PORTFOLIO YIELD</small><strong>{m.yieldPct.toFixed(2)}%</strong><span>${m.annualIncome.toFixed(0)} annualized</span></article></section>
 <section className="mission-grid"><article className="panel mission-span-2"><div className="panel-title"><span>INCOME FLIGHT PLAN</span><b>{m.goalProgress.toFixed(0)}%</b></div><div className="goal-track"><span style={{width:`${Math.min(100,m.goalProgress)}%`}}/></div><div className="flight-stats"><div><small>CURRENT</small><strong>${m.weeklyIncome.toFixed(0)}/wk</strong></div><div><small>TARGET</small><strong>${weeklyGoal.toLocaleString()}/wk</strong></div><div><small>GAP</small><strong>${Math.max(0,weeklyGoal-m.weeklyIncome).toFixed(0)}/wk</strong></div></div></article><PortfolioHealthCard/></section>
 <section className="mission-grid"><article className="panel"><div className="panel-title"><span>NEXT CASH EVENTS</span><CalendarClock size={16}/></div><div className="cash-events">{events.slice(0,7).map(e=><div key={e.id}><time>{new Date(e.date).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</time><b>{e.ticker}</b><span>{e.type}</span><strong>${e.amount.toFixed(0)}</strong></div>)}</div></article><article className="panel"><div className="panel-title"><span>INTELLIGENCE FEED</span><Sparkles size={16}/></div><div className="mission-alerts">{alerts.map(a=><div className={a.severity} key={a.id}><AlertTriangle size={15}/><p><b>{a.title}</b><span>{a.detail}</span><small>{a.source}</small></p></div>)}</div></article></section>
 <section className="panel copilot-console"><div className="copilot-title"><Bot/><div><span>INCOME COPILOT™</span><small>Explainable answers grounded in portfolio rules and calculations</small></div></div><div className="copilot-answer"><b>{answer.headline}</b><p>{answer.answer}</p><ul>{answer.evidence.map(x=><li key={x}>{x}</li>)}</ul><small>Confidence: {answer.confidence}</small></div><div className="copilot-input"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()} aria-label="Ask Income Copilot"/><button onClick={submit}><Send size={15}/>Ask</button></div><div className="copilot-prompts">{['What is my biggest risk?','Which ETF contributes the most income?','Am I on track for my goal?'].map(x=><button key={x} onClick={()=>{setQ(x);setAnswer(askIncomeCopilot(x,holdings,m.weeklyIncome,weeklyGoal))}}>{x}</button>)}</div></section></div>
}
