import { AlertTriangle, Cloud, CloudOff, Download, Pencil, Plus, RefreshCw, ShieldCheck, Trash2, X } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { holdingsToCsv, portfolioDataQuality, validateHolding, type HoldingDraft } from '../features/portfolio/portfolioManagement'
import { usePortfolio, usePortfolioMetrics } from '../features/portfolio/PortfolioContext'
import type { Holding } from '../types/portfolio'
import { transactionCashFlow, transactionSummary, validateTransaction } from '../features/portfolio/transactionEngine'
import type { TransactionType } from '../types/portfolio'
import { availableShares } from '../features/portfolio/positionEngine'

const money = (value: number, digits = 2) => value.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:digits})
const blankHolding: HoldingDraft = { ticker:'', fundName:'', shares:0, averageCost:0, currentPrice:0, annualDistributionPerShare:0, paymentFrequency:'Weekly', category:'Covered Call' }
const today = new Date().toISOString().slice(0,10)

export function PortfolioPage(){
 const {holdings,transactions,addHolding,updateHolding,removeHolding,recordTransaction,removeTransaction,syncState,syncError,refreshPortfolio}=usePortfolio(); const metrics=usePortfolioMetrics()
 const [editing,setEditing]=useState<Holding | null>(null); const [holdingOpen,setHoldingOpen]=useState(false); const [transactionOpen,setTransactionOpen]=useState(false); const [errors,setErrors]=useState<string[]>([])
 const quality=useMemo(()=>portfolioDataQuality(holdings),[holdings]); const ledger=useMemo(()=>transactionSummary(transactions),[transactions])
 const startAdd=()=>{setEditing(null);setErrors([]);setHoldingOpen(true)}; const startEdit=(holding:Holding)=>{setEditing(holding);setErrors([]);setHoldingOpen(true)}
 function submitHolding(e:FormEvent<HTMLFormElement>){
  e.preventDefault(); const f=new FormData(e.currentTarget)
  const result=validateHolding({ticker:String(f.get('ticker')),fundName:String(f.get('fundName')),shares:Number(f.get('shares')),averageCost:Number(f.get('averageCost')),currentPrice:Number(f.get('currentPrice')),annualDistributionPerShare:Number(f.get('annualDistributionPerShare')),paymentFrequency:String(f.get('paymentFrequency')) as Holding['paymentFrequency'],category:String(f.get('category'))})
  if(!result.valid){setErrors(result.errors);return} const duplicate=holdings.find(h=>h.ticker===result.holding.ticker&&h.id!==editing?.id)
  if(duplicate){setErrors([`${result.holding.ticker} already exists. Edit the existing position instead.`]);return}
  editing?updateHolding(editing.id,result.holding):addHolding(result.holding); setHoldingOpen(false); setEditing(null)
 }
 async function submitTransaction(e:FormEvent<HTMLFormElement>){
  e.preventDefault(); const f=new FormData(e.currentTarget); const ticker=String(f.get('ticker')); const holding=holdings.find(h=>h.ticker===ticker)
  const result=validateTransaction({holdingId:holding?.id??null,ticker,type:String(f.get('type')) as TransactionType,tradeDate:String(f.get('tradeDate')),shares:Number(f.get('shares')),price:Number(f.get('price')),fees:Number(f.get('fees')),notes:String(f.get('notes'))})
  if(!result.valid){setErrors(result.errors);return}
  if(result.transaction.type==='sell'){const available=availableShares(result.transaction.ticker??'',holdings,transactions);if(result.transaction.shares>available+1e-8){setErrors([`Sell exceeds available shares. ${result.transaction.ticker} has ${available.toLocaleString()} shares available.`]);return}}
  try{await recordTransaction(result.transaction);setTransactionOpen(false);setErrors([])}catch{/* context exposes error */}
 }
 function exportCsv(){const url=URL.createObjectURL(new Blob([holdingsToCsv(holdings)],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`incomeos-portfolio-${today}.csv`;a.click();URL.revokeObjectURL(url)}
 const defaults=editing??blankHolding; const syncLabel={loading:'Loading portfolio',saving:'Saving changes',synced:'Cloud synchronized',offline:'Local demo storage',error:'Sync attention required'}[syncState]
 return <div><section className="page-heading"><div><span className="eyebrow">ENTERPRISE EDITION v1.8 · PHASE 1 MILESTONE 3C</span><h1>Portfolio Health & Reconciliation</h1><p>Reconcile holdings, transactions, prices, and distributions through a prioritized investor action center.</p></div><div className="portfolio-actions"><button className="secondary-action" onClick={()=>void refreshPortfolio()}><RefreshCw size={16}/> Refresh</button><button className="secondary-action" onClick={exportCsv} disabled={!holdings.length}><Download size={16}/> Export CSV</button><button className="secondary-action" onClick={()=>{setErrors([]);setTransactionOpen(true)}}><Plus size={16}/> Transaction</button><button className="gold-button" onClick={startAdd}><Plus size={16}/> Add Holding</button></div></section>
 <div className={`sync-banner ${syncState}`}>{syncState==='offline'?<CloudOff size={17}/>:<Cloud size={17}/>}<div><strong>{syncLabel}</strong><small>{syncError??(syncState==='offline'?'Connect Supabase to synchronize across devices.':'Portfolio changes are stored against the signed-in user account.')}</small></div></div>
 <section className="metric-grid small"><Metric label="Market Value" value={money(metrics.portfolioValue,0)}/><Metric label="Cost Basis" value={money(metrics.costBasis,0)}/><Metric label="Unrealized Gain/Loss" value={money(metrics.gainLoss,0)}/><Metric label="Realized Gain/Loss" value={money(metrics.realizedGain,0)}/></section>
 <section className="health-overview"><article className="panel health-score"><ShieldCheck size={24}/><div><span className="terminal-label">PORTFOLIO HEALTH</span><strong>{metrics.portfolioHealth.score}</strong><small>{metrics.portfolioHealth.grade}</small></div></article><article className="panel action-center"><div className="panel-heading"><div><h3>Investor Action Center</h3><small>Prioritized reconciliation and data-quality issues</small></div><span>{metrics.portfolioHealth.alerts.length} open</span></div>{metrics.portfolioHealth.alerts.slice(0,6).map(alert=><div className={`health-alert ${alert.severity}`} key={alert.id}><AlertTriangle size={16}/><div><strong>{alert.title}{alert.ticker?` · ${alert.ticker}`:""}</strong><p>{alert.detail}</p><small>{alert.action}</small></div><span>{alert.severity}</span></div>)}{!metrics.portfolioHealth.alerts.length&&<div className="empty-state"><strong>Portfolio reconciled</strong><span>No material health or data-quality issues were found.</span></div>}</article></section>
 <article className="panel portfolio-quality"><div><ShieldCheck size={20}/><div><span className="terminal-label">DATA QUALITY</span><strong>{quality.score}% complete</strong><small>{quality.complete} of {quality.total} positions have price, cost basis, and distribution data.</small></div></div>{quality.issues.length>0&&<div className="quality-issues">{quality.issues.slice(0,4).map(issue=><span key={issue}>{issue}</span>)}</div>}</article>
 <article className="panel portfolio-quality"><div><ShieldCheck size={20}/><div><span className="terminal-label">LEDGER COVERAGE</span><strong>{metrics.ledgerCoveragePct.toFixed(0)}% transaction-derived</strong><small>Positions with buy or sell history use weighted-average cost calculations. Manual positions remain available as an opening-balance fallback.</small></div></div>{metrics.calculationWarnings.length>0&&<div className="quality-issues">{metrics.calculationWarnings.slice(0,4).map(issue=><span key={issue}>{issue}</span>)}</div>}</article>
 <article className="panel holdings-panel"><div className="panel-heading"><div><h3>Calculated Positions</h3><small>Weighted-average cost basis with realized and unrealized gain/loss</small></div><span>{metrics.positions.length} positions</span></div><div className="holdings-table calculated-table"><div className="holding-row holding-head"><span>Ticker / Source</span><span>Shares</span><span>Avg. Cost</span><span>Market Value</span><span>Unrealized</span><span>Realized</span><span></span></div>{metrics.positions.map(position=>{const holding=holdings.find(h=>h.ticker===position.ticker);return <div className="holding-row" key={position.ticker}><span><strong className="ticker">{position.ticker}</strong><small>{position.source==='ledger'?'LEDGER DERIVED':'MANUAL OPENING BALANCE'} · {position.fundName}</small></span><span>{position.shares.toLocaleString(undefined,{maximumFractionDigits:6})}</span><span>{money(position.averageCost)}</span><strong>{money(position.marketValue,0)}</strong><strong className={position.unrealizedGain>=0?'positive':'negative'}>{money(position.unrealizedGain,0)}</strong><span className={position.realizedGain>=0?'positive':'negative'}>{money(position.realizedGain,0)}</span><span className="row-actions">{holding&&<><button className="icon-button" onClick={()=>startEdit(holding)} aria-label={`Edit ${holding.ticker}`}><Pencil size={15}/></button><button className="delete-button" onClick={()=>removeHolding(holding.id)} aria-label={`Remove ${holding.ticker}`}><Trash2 size={15}/></button></>}</span></div>})}{!metrics.positions.length&&<div className="empty-state"><strong>No calculated positions</strong><span>Add a holding or record a buy transaction to begin.</span></div>}</div></article>
 <article className="panel transaction-panel"><div className="panel-heading"><div><h3>Transaction Ledger</h3><small>Buys, sells, distributions, cash movements, and fees</small></div><span>{transactions.length} entries</span></div><div className="transaction-summary"><span>Invested <strong>{money(ledger.invested,0)}</strong></span><span>Sale proceeds <strong>{money(ledger.proceeds,0)}</strong></span><span>Distributions <strong>{money(ledger.distributions,0)}</strong></span></div><div className="transaction-list">{transactions.slice(0,12).map(t=><div className="transaction-row" key={t.id}><span><strong>{t.type.toUpperCase()}</strong><small>{t.tradeDate}</small></span><span><b>{t.ticker||'CASH'}</b><small>{t.notes||'No note'}</small></span><span className={transactionCashFlow(t)>=0?'positive':''}>{money(transactionCashFlow(t))}</span><button className="delete-button" onClick={()=>void removeTransaction(t.id)} aria-label="Delete transaction"><Trash2 size={14}/></button></div>)}{!transactions.length&&<div className="empty-state"><strong>No transactions recorded</strong><span>Add the first ledger entry to begin an auditable portfolio history.</span></div>}</div></article>
 {holdingOpen&&<div className="modal-backdrop"><form className="modal" onSubmit={submitHolding}><ModalTitle label={editing?'POSITION MAINTENANCE':'NEW POSITION'} title={editing?`Edit ${editing.ticker}`:'Add Holding'} close={()=>setHoldingOpen(false)}/><Errors errors={errors}/><div className="form-grid"><label>Ticker<input name="ticker" required defaultValue={defaults.ticker}/></label><label>Fund name<input name="fundName" required defaultValue={defaults.fundName}/></label><label>Shares<input name="shares" type="number" min="0.000001" step="0.000001" required defaultValue={defaults.shares||''}/></label><label>Average cost<input name="averageCost" type="number" min="0" step="0.01" required defaultValue={defaults.averageCost||''}/></label><label>Current price<input name="currentPrice" type="number" min="0" step="0.01" required defaultValue={defaults.currentPrice||''}/></label><label>Annual distribution/share<input name="annualDistributionPerShare" type="number" min="0" step="0.01" required defaultValue={defaults.annualDistributionPerShare||''}/></label><label>Frequency<select name="paymentFrequency" defaultValue={defaults.paymentFrequency}><option>Weekly</option><option>Monthly</option><option>Quarterly</option></select></label><label>Category<select name="category" defaultValue={defaults.category}><option>Covered Call</option><option>Equity Income</option><option>Crypto Income</option><option>Bond Income</option><option>Other</option></select></label></div><button className="gold-button full" type="submit">{editing?'Save Changes':'Add to Portfolio'}</button></form></div>}
 {transactionOpen&&<div className="modal-backdrop"><form className="modal" onSubmit={submitTransaction}><ModalTitle label="AUDITABLE LEDGER" title="Record Transaction" close={()=>setTransactionOpen(false)}/><Errors errors={errors}/><div className="form-grid"><label>Type<select name="type" defaultValue="buy"><option value="buy">Buy</option><option value="sell">Sell</option><option value="dividend">Dividend</option><option value="deposit">Deposit</option><option value="withdrawal">Withdrawal</option><option value="fee">Fee</option></select></label><label>Date<input name="tradeDate" type="date" required defaultValue={today}/></label><label>Ticker<select name="ticker" defaultValue={holdings[0]?.ticker??''}><option value="">Cash / none</option>{holdings.map(h=><option key={h.id}>{h.ticker}</option>)}</select></label><label>Shares<input name="shares" type="number" min="0" step="0.000001" defaultValue="0"/></label><label>Price or cash amount<input name="price" type="number" min="0" step="0.01" required defaultValue="0"/></label><label>Fees<input name="fees" type="number" min="0" step="0.01" defaultValue="0"/></label><label className="full-field">Notes<input name="notes" placeholder="Broker confirmation, reinvestment, or reconciliation note"/></label></div><button className="gold-button full" type="submit">Save Transaction</button></form></div>}
 </div>}
function Metric({label,value}:{label:string,value:string}){return <article className="metric-card simple"><span>{label}</span><strong>{value}</strong></article>}
function Errors({errors}:{errors:string[]}){return errors.length?<div className="form-errors">{errors.map(error=><p key={error}>{error}</p>)}</div>:null}
function ModalTitle({label,title,close}:{label:string,title:string,close:()=>void}){return <div className="modal-title"><div><span className="eyebrow">{label}</span><h2>{title}</h2></div><button type="button" className="icon-button" aria-label="Close dialog" onClick={close}><X/></button></div>}
