import { useMemo, useState } from 'react'
import { buildOperationsSnapshot, decideAlert, type BackupVerification, type HealthCheck, type Incident } from '../services/production/operationsMonitoring'
import { loadProductionOperations, saveProductionOperations } from '../features/operations/productionOperationsRepository'

const now=()=>new Date().toISOString()
const seedChecks:HealthCheck[]=[
 {id:'web',name:'Web application',status:'operational',latencyMs:128,checkedAt:now(),detail:'Frontend route and asset checks passed.'},
 {id:'database',name:'Portfolio database',status:'operational',latencyMs:84,checkedAt:now(),detail:'Authenticated database probe passed.'},
 {id:'jobs',name:'Background jobs',status:'unknown',latencyMs:null,checkedAt:now(),detail:'Configure the server worker endpoint for unattended execution.'},
]
export function ProductionOperationsPage(){
 const initial=loadProductionOperations(); const [checks,setChecks]=useState(initial.checks.length?initial.checks:seedChecks); const [incidents,setIncidents]=useState<Incident[]>(initial.incidents); const [backups,setBackups]=useState<BackupVerification[]>(initial.backups); const [maintenance,setMaintenance]=useState(initial.maintenance)
 const snapshot=useMemo(()=>buildOperationsSnapshot({checks,incidents,backups,maintenance}),[checks,incidents,backups,maintenance])
 const persist=(next:{checks?:HealthCheck[];incidents?:Incident[];backups?:BackupVerification[];maintenance?:boolean})=>saveProductionOperations({checks:next.checks??checks,incidents:next.incidents??incidents,backups:next.backups??backups,maintenance:next.maintenance??maintenance})
 const runChecks=()=>{const updated=checks.map(c=>({...c,checkedAt:now(),status:c.id==='jobs'&&c.status==='unknown'?'degraded':c.status,detail:c.id==='jobs'&&c.status==='unknown'?'Server worker has not reported a successful run.':c.detail} as HealthCheck));setChecks(updated);persist({checks:updated})}
 const addIncident=()=>{const incident:Incident={id:crypto.randomUUID(),title:'Manual operations review',severity:'warning',status:'open',startedAt:now(),resolvedAt:null,message:'Operator-created incident for follow-up.'};const updated=[incident,...incidents];setIncidents(updated);persist({incidents:updated})}
 const verifyBackup=()=>{const item:BackupVerification={id:crypto.randomUUID(),backupAt:now(),verifiedAt:now(),restoreTestedAt:now(),status:'verified',notes:'Manual restore verification recorded.'};const updated=[item,...backups];setBackups(updated);persist({backups:updated})}
 const toggleMaintenance=()=>{const value=!maintenance;setMaintenance(value);persist({maintenance:value})}
 return <section className="page-stack"><header className="page-header"><div><span className="eyebrow">Phase 3 · Milestone 2</span><h1>Production Operations</h1><p>Monitoring, incidents, recovery verification, job reliability, and launch operations for IncomeOS v3.1.</p></div><div className="header-actions"><button className="primary-button" onClick={runChecks}>Run health checks</button><button className="secondary-button" onClick={toggleMaintenance}>{maintenance?'End maintenance':'Start maintenance'}</button></div></header>
 <div className="status-grid"><article className="terminal-card"><span>System status</span><strong>{snapshot.overall.toUpperCase()}</strong><p>{snapshot.availabilityPct}% service availability</p></article><article className="terminal-card"><span>Open incidents</span><strong>{snapshot.openIncidents}</strong><p>{snapshot.criticalIncidents} critical</p></article><article className="terminal-card"><span>Backup posture</span><strong>{snapshot.backupStatus.toUpperCase()}</strong><p>{backups.length?`${backups.length} verification record(s)`:'No restore verification recorded'}</p></article></div>
 <article className="terminal-card"><div className="card-heading"><div><h2>Service health</h2><p>Latest synthetic and dependency checks.</p></div></div>{checks.map(c=><div className="config-issue" key={c.id}><strong className={`status-${c.status==='operational'?'healthy':c.status==='outage'?'unhealthy':'not-configured'}`}>{c.status.toUpperCase()} · {c.name}</strong><p>{c.detail} {c.latencyMs!==null?`(${c.latencyMs} ms)`:''}</p><small>{new Date(c.checkedAt).toLocaleString()}</small></div>)}</article>
 <div className="two-column"><article className="terminal-card"><div className="card-heading"><div><h2>Incident command</h2><p>Escalation and response records.</p></div><button className="secondary-button" onClick={addIncident}>Create incident</button></div>{incidents.length?incidents.map(i=>{const alert=decideAlert(i);return <div className="config-issue" key={i.id}><strong>{i.severity.toUpperCase()} · {i.title}</strong><p>{i.message}</p><small>{i.status} · {alert.notify?`Escalate by ${alert.channel}`:'No escalation'}</small></div>}):<p>No incidents recorded.</p>}</article><article className="terminal-card"><div className="card-heading"><div><h2>Backup & recovery</h2><p>Record restore verification evidence.</p></div><button className="secondary-button" onClick={verifyBackup}>Verify restore</button></div>{backups.length?backups.slice(0,5).map(b=><div className="config-issue" key={b.id}><strong>{b.status.toUpperCase()} · {new Date(b.backupAt).toLocaleString()}</strong><p>{b.notes}</p></div>):<p>No backup verification has been recorded.</p>}</article></div>
 <article className="terminal-card"><h2>Production operating controls</h2><ul className="release-gates"><li>Server cron or queue worker invokes secured market and distribution jobs</li><li>Structured client and server events are retained for audit and troubleshooting</li><li>Critical incidents escalate immediately; repeated failures trigger paging</li><li>Post-deployment smoke tests validate routes, authentication, database access, and job health</li><li>Rollback and restore procedures are documented and periodically tested</li></ul></article></section>
}
