import { CheckCircle2, CircleAlert, Download, SlidersHorizontal, Sparkles, Target, TrendingUp } from 'lucide-react'
import { useMemo, useState } from 'react'
import { rankStrategies } from '../domain/strategy-builder/engine'
import { STRATEGY_TEMPLATES } from '../domain/strategy-builder/templates'
import type { GeneratedStrategy, StrategyBuilderProfile, StrategyConstraints } from '../domain/strategy-builder/types'
import { createStrategyReport, downloadStrategyReport } from '../services/reports/strategyReport'

const money=(v:number)=>v.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})
const initialProfile:StrategyBuilderProfile={name:'My Income Strategy',investableCapital:350000,targetWeeklyIncome:2000,monthlyContribution:0,reinvestmentPct:25,horizonYears:10,accountType:'Taxable',maximumDrawdownPct:25,incomePriority:65,growthPriority:35,distributionPreference:'Weekly preferred',riskTolerance:'Moderate'}
const initialConstraints:StrategyConstraints={minimumHoldings:5,maximumSingleEtfPct:25,maximumSingleIssuerPct:35,maximumCoveredCallPct:35,minimumGrowthPct:30,minimumFixedIncomePct:10,maximumSectorPct:40}

function Score({label,value}:{label:string;value:number}){return <div className="builder-score"><span>{label}</span><strong>{value}</strong><i><b style={{width:`${value}%`}}/></i></div>}

export function IncomeStrategyBuilderPage(){
 const [profile,setProfile]=useState(initialProfile); const [constraints,setConstraints]=useState(initialConstraints); const [selected,setSelected]=useState('balanced'); const [compareIds,setCompareIds]=useState(['balanced','conservative','max-income'])
 const results=useMemo(()=>rankStrategies(STRATEGY_TEMPLATES,profile,constraints),[profile,constraints]); const active=results.find(r=>r.id===selected)??results[0]; const compared=compareIds.map(id=>results.find(r=>r.id===id)).filter(Boolean) as GeneratedStrategy[]
 const updateProfile=<K extends keyof StrategyBuilderProfile>(key:K,value:StrategyBuilderProfile[K])=>setProfile(p=>({...p,[key]:value})); const updateConstraint=<K extends keyof StrategyConstraints>(key:K,value:StrategyConstraints[K])=>setConstraints(p=>({...p,[key]:value}))
 const applyTemplate=(id:string)=>{const t=STRATEGY_TEMPLATES.find(x=>x.id===id);if(!t)return;setProfile(p=>({...p,...t.profilePatch}));setConstraints(c=>({...c,...t.constraintPatch}));setSelected(id)}
 return <div className="strategy-builder-page">
  <section className="page-heading"><div><span className="eyebrow">INCOME OPERATING SYSTEM</span><h1>Income Strategy Builder™</h1><p>Define your goals, apply transparent constraints, and compare modeled income strategies side by side.</p></div><button className="gold-button" onClick={()=>downloadStrategyReport(createStrategyReport(profile,constraints,results))}><Download size={15}/> Export Strategy Report</button></section>
  <section className="builder-stepbar"><span className="active">1 Goals</span><span>2 Constraints</span><span>3 Templates</span><span>4 Optimize</span><span>5 Compare</span><span>6 Report</span></section>
  <section className="builder-grid">
   <article className="panel builder-controls"><div className="panel-heading"><h3><Target size={16}/> Goals and assumptions</h3><span>STEP 1</span></div>
    <div className="control-grid"><label>Investable capital<input type="number" value={profile.investableCapital} onChange={e=>updateProfile('investableCapital',Number(e.target.value))}/></label><label>Target weekly income<input type="number" value={profile.targetWeeklyIncome} onChange={e=>updateProfile('targetWeeklyIncome',Number(e.target.value))}/></label><label>Monthly contribution<input type="number" value={profile.monthlyContribution} onChange={e=>updateProfile('monthlyContribution',Number(e.target.value))}/></label><label>Horizon (years)<input type="number" min="1" max="40" value={profile.horizonYears} onChange={e=>updateProfile('horizonYears',Number(e.target.value))}/></label></div>
    <label className="builder-range">Reinvest distributions <strong>{profile.reinvestmentPct}%</strong><input type="range" min="0" max="100" value={profile.reinvestmentPct} onChange={e=>updateProfile('reinvestmentPct',Number(e.target.value))}/></label>
    <label className="builder-range">Income priority <strong>{profile.incomePriority}%</strong><input type="range" min="0" max="100" value={profile.incomePriority} onChange={e=>{const v=Number(e.target.value);setProfile(p=>({...p,incomePriority:v,growthPriority:100-v}))}}/></label>
    <label className="builder-range">Growth priority <strong>{profile.growthPriority}%</strong><input type="range" min="0" max="100" value={profile.growthPriority} readOnly/></label>
    <div className="control-grid"><label>Risk tolerance<select value={profile.riskTolerance} onChange={e=>updateProfile('riskTolerance',e.target.value as StrategyBuilderProfile['riskTolerance'])}><option>Conservative</option><option>Moderate</option><option>Growth</option><option>Aggressive</option></select></label><label>Distribution preference<select value={profile.distributionPreference} onChange={e=>updateProfile('distributionPreference',e.target.value as StrategyBuilderProfile['distributionPreference'])}><option>Weekly preferred</option><option>Monthly preferred</option><option>No preference</option></select></label></div>
   </article>
   <article className="panel builder-controls"><div className="panel-heading"><h3><SlidersHorizontal size={16}/> Portfolio constraints</h3><span>STEP 2</span></div>
    <div className="control-grid">{([
     ['minimumHoldings','Minimum holdings'],['maximumSingleEtfPct','Max single ETF %'],['maximumSingleIssuerPct','Max issuer %'],['maximumCoveredCallPct','Max covered-call %'],['minimumGrowthPct','Minimum growth %'],['minimumFixedIncomePct','Minimum fixed income %'],['maximumSectorPct','Max sector %']
    ] as const).map(([key,label])=><label key={key}>{label}<input type="number" min="0" max="100" value={constraints[key]} onChange={e=>updateConstraint(key,Number(e.target.value))}/></label>)}</div>
   </article>
  </section>
  <section className="panel template-panel"><div className="panel-heading"><h3><Sparkles size={16}/> Strategy templates</h3><span>STEP 3</span></div><div className="template-grid">{STRATEGY_TEMPLATES.map(t=><button key={t.id} className={active.id===t.id?'active':''} onClick={()=>applyTemplate(t.id)}><strong>{t.name}</strong><span>{t.description}</span></button>)}</div></section>
  <section className="builder-results-grid">
   <article className="panel"><div className="panel-heading"><h3><TrendingUp size={16}/> Optimized result</h3><span className="live-badge">RANK #{results.findIndex(r=>r.id===active.id)+1}</span></div><div className="strategy-result-hero"><div><small>{active.name}</small><strong>{money(active.projectedWeeklyIncome)}<em>/week</em></strong><span>{active.goalProgressPct.toFixed(0)}% of target · {active.modeledYieldPct.toFixed(2)}% modeled yield</span></div><div className="overall-score"><strong>{active.scores.overall}</strong><span>Overall fit</span></div></div>
    <div className="builder-score-grid"><Score label="Income potential" value={active.scores.incomePotential}/><Score label="Growth potential" value={active.scores.growthPotential}/><Score label="Diversification" value={active.scores.diversification}/><Score label="Income stability" value={active.scores.incomeStability}/><Score label="Risk fit" value={active.scores.riskFit}/><Score label="Goal alignment" value={active.scores.goalAlignment}/></div>
    <div className="allocation-table"><div className="allocation-row head"><span>Model holding</span><span>Allocation</span><span>Dollars</span><span>Annual income</span></div>{active.allocations.map(a=><div className="allocation-row" key={a.ticker}><span><b>{a.ticker}</b><small>{a.name}</small></span><span>{a.allocationPct.toFixed(1)}%</span><span>{money(a.dollars)}</span><span>{money(a.annualIncome)}</span></div>)}</div>
   </article>
   <article className="panel"><div className="panel-heading"><h3>Goal Alignment Engine</h3><span>STEP 6</span></div><div className="constraint-list">{active.checks.map(c=><div className={c.passed?'passed':'failed'} key={c.label}>{c.passed?<CheckCircle2 size={16}/>:<CircleAlert size={16}/>}<span><strong>{c.label}</strong><small>Actual {c.actual.toFixed(c.unit==='count'?0:1)}{c.unit==='%'?'%':''} · threshold {c.limit}{c.unit==='%'?'%':''}</small></span></div>)}</div><div className="strategy-observations"><h4>Explainable observations</h4>{active.observations.map(o=><p key={o}>{o}</p>)}</div></article>
  </section>
  <section className="panel comparison-lab"><div className="panel-heading"><h3>Scenario Comparison Studio</h3><span>STEP 5</span></div><div className="comparison-selects">{compareIds.map((id,index)=><select key={index} value={id} onChange={e=>setCompareIds(ids=>ids.map((x,i)=>i===index?e.target.value:x))}>{STRATEGY_TEMPLATES.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>)}</div><div className="strategy-comparison-grid">{compared.map(r=><article key={r.id}><h4>{r.name}</h4><strong>{money(r.projectedWeeklyIncome)} / week</strong><span>{r.modeledYieldPct.toFixed(2)}% yield · {r.modeledGrowthPct.toFixed(2)}% growth</span><dl><div><dt>Overall fit</dt><dd>{r.scores.overall}</dd></div><div><dt>Goal alignment</dt><dd>{r.scores.goalAlignment}</dd></div><div><dt>Constraints passed</dt><dd>{r.checks.filter(c=>c.passed).length}/{r.checks.length}</dd></div><div><dt>Year {profile.horizonYears} value</dt><dd>{money(r.projection.at(-1)?.portfolioValue??profile.investableCapital)}</dd></div></dl><button className="secondary-button" onClick={()=>setSelected(r.id)}>View allocation</button></article>)}</div></section>
  <p className="data-disclaimer">Educational planning model only. Candidate symbols and assumptions in this offline increment are clearly labeled placeholders. They are not live ETF recommendations, forecasts, or verified market data.</p>
 </div>
}
