import type { StrategyTemplate } from './types'

export const STRATEGY_TEMPLATES: StrategyTemplate[] = [
  {id:'balanced',name:'Income + Growth',description:'Balances current distributions with long-term upside participation.',profilePatch:{incomePriority:55,growthPriority:45,riskTolerance:'Moderate',reinvestmentPct:35},constraintPatch:{maximumCoveredCallPct:35,minimumGrowthPct:35,minimumFixedIncomePct:10},categoryTargets:{'Core Equity':20,'Dividend Growth':25,'Covered Call':30,'Fixed Income':15,'REIT':10}},
  {id:'conservative',name:'Conservative Income',description:'Prioritizes stability, diversification and lower modeled drawdown.',profilePatch:{incomePriority:65,growthPriority:35,riskTolerance:'Conservative',maximumDrawdownPct:15,reinvestmentPct:25},constraintPatch:{maximumCoveredCallPct:20,minimumGrowthPct:20,minimumFixedIncomePct:35},categoryTargets:{'Dividend Growth':20,'Covered Call':15,'Fixed Income':40,'Preferreds':15,'REIT':10}},
  {id:'max-income',name:'Income Maximizer',description:'Targets higher current income while enforcing concentration limits.',profilePatch:{incomePriority:85,growthPriority:15,riskTolerance:'Aggressive',reinvestmentPct:20},constraintPatch:{maximumCoveredCallPct:55,minimumGrowthPct:10,minimumFixedIncomePct:5},categoryTargets:{'Covered Call':50,'Alternative Income':10,'Fixed Income':10,'Preferreds':15,'REIT':15}},
  {id:'retirement',name:'Retirement Income',description:'Mixes dependable monthly cash flow with inflation-sensitive growth assets.',profilePatch:{incomePriority:70,growthPriority:30,riskTolerance:'Moderate',reinvestmentPct:15,distributionPreference:'Monthly preferred'},constraintPatch:{maximumCoveredCallPct:30,minimumGrowthPct:25,minimumFixedIncomePct:25},categoryTargets:{'Dividend Growth':25,'Covered Call':25,'Fixed Income':30,'Preferreds':10,'REIT':10}},
  {id:'div-growth',name:'Dividend Growth',description:'Emphasizes quality equity and income growth over maximum starting yield.',profilePatch:{incomePriority:35,growthPriority:65,riskTolerance:'Growth',reinvestmentPct:75},constraintPatch:{maximumCoveredCallPct:15,minimumGrowthPct:65,minimumFixedIncomePct:5},categoryTargets:{'Core Equity':30,'Dividend Growth':45,'Covered Call':10,'Fixed Income':5,'REIT':10}},
  {id:'weekly',name:'Weekly Cash Flow',description:'Prefers weekly distributions while retaining stabilizing allocations.',profilePatch:{incomePriority:75,growthPriority:25,distributionPreference:'Weekly preferred',riskTolerance:'Moderate'},constraintPatch:{maximumCoveredCallPct:45,minimumGrowthPct:20,minimumFixedIncomePct:15},categoryTargets:{'Dividend Growth':20,'Covered Call':40,'Fixed Income':20,'Preferreds':10,'REIT':10}},
]
