create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  timezone text not null default 'America/New_York',
  accepted_terms_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.user_profiles enable row level security;
create policy "profiles_select_own" on public.user_profiles for select using (auth.uid() = user_id);
create policy "profiles_insert_own" on public.user_profiles for insert with check (auth.uid() = user_id);
create policy "profiles_update_own" on public.user_profiles for update using (auth.uid() = user_id);

create table if not exists public.security_audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  severity text not null default 'info' check (severity in ('info','warning','critical')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.security_audit_log enable row level security;
create policy "audit_select_own" on public.security_audit_log for select using (auth.uid() = user_id);
create policy "audit_insert_own" on public.security_audit_log for insert with check (auth.uid() = user_id);
create index if not exists security_audit_log_user_created_idx on public.security_audit_log(user_id, created_at desc);
